FROM python:3.11-slim

WORKDIR /app/ui

COPY ui/ /app/ui
COPY requirements.txt /app

RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
