market_basket_analysis:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: fp_growth_mba
      schema: public
      threads: 4
      keepalives_idle: 0